#!/bin/sh

. /etc/openwrt_release

CPUINFO_PATH="/proc/cpuinfo"
CPUFREQ_PATH="/sys/devices/system/cpu/cpufreq"
THERMAL_PATH="/sys/class/thermal"
HWMON_PATH="/sys/class/hwmon"

format_temp_file() {
	awk '
	/^[+-]?[0-9]+(\.[0-9]+)?$/ {
		temp = $1 + 0
		if (temp > 1000 || temp < -1000)
			temp = temp / 1000
		if (temp > 0 && temp < 130) {
			printf("%.1f°C", temp)
			exit
		}
	}' "$1" 2>"/dev/null"
}

read_temp_from_hwmon() {
	for hwmon in "$HWMON_PATH"/hwmon*; do
		[ -d "$hwmon" ] || continue

		name="$(cat "$hwmon/name" 2>"/dev/null")"
		case "$name" in
		coretemp|k10temp|zenpower|x86_pkg_temp|cpu_thermal|cpu-thermal|soc_dts*)
			for input in "$hwmon"/temp*_input; do
				[ -r "$input" ] || continue
				temp="$(format_temp_file "$input")"
				[ -n "$temp" ] && {
					echo -n "$temp"
					return 0
				}
			done
			;;
		esac
	done

	for hwmon in "$HWMON_PATH"/hwmon*; do
		[ -d "$hwmon" ] || continue

		name="$(cat "$hwmon/name" 2>"/dev/null")"
		case "$name" in
		acpitz|pch_*|INT34*)
			for input in "$hwmon"/temp*_input; do
				[ -r "$input" ] || continue
				temp="$(format_temp_file "$input")"
				[ -n "$temp" ] && {
					echo -n "$temp"
					return 0
				}
			done
			;;
		esac
	done

	return 1
}

read_temp_from_thermal_zone() {
	for zone in "$THERMAL_PATH"/thermal_zone*; do
		[ -r "$zone/temp" ] || continue

		type="$(cat "$zone/type" 2>"/dev/null")"
		case "$type" in
		*x86_pkg_temp*|*coretemp*|*Core*|*core*|*soc_dts*|*SoC*|*soc*|*CPU*|*cpu*)
			temp="$(format_temp_file "$zone/temp")"
			[ -n "$temp" ] && {
				echo -n "$temp"
				return 0
			}
			;;
		esac
	done

	for zone in "$THERMAL_PATH"/thermal_zone*; do
		[ -r "$zone/temp" ] || continue

		type="$(cat "$zone/type" 2>"/dev/null")"
		case "$type" in
		*acpitz*|*Thermal*|*thermal*|*pch*|*INT34*)
			temp="$(format_temp_file "$zone/temp")"
			[ -n "$temp" ] && {
				echo -n "$temp"
				return 0
			}
			;;
		esac
	done

	for zone in "$THERMAL_PATH"/thermal_zone*; do
		[ -r "$zone/temp" ] || continue

		temp="$(format_temp_file "$zone/temp")"
		[ -n "$temp" ] && {
			echo -n "$temp"
			return 0
		}
	done

	return 1
}

read_cpu_temp() {
	temp="$(read_temp_from_hwmon)"
	[ -n "$temp" ] && {
		echo -n "$temp"
		return 0
	}

	read_temp_from_thermal_zone
}

cpu_arch="$(awk -F ': ' '/model name/ {print $2}' "$CPUINFO_PATH" | head -n1)"
[ -n "${cpu_arch}" ] || cpu_arch="?"

case "$DISTRIB_TARGET" in
"x86"/*)
	cpu_cores="$(grep "core id" "$CPUINFO_PATH" | sort -u | wc -l)C $(grep -c "processor" "$CPUINFO_PATH")T" ;;
*)
	cpu_cores="$(grep -c "processor" "$CPUINFO_PATH")" ;;
esac

case "$DISTRIB_TARGET" in
"bcm27xx"/*)
	cpu_freq="$(( $(vcgencmd measure_clock arm | awk -F '=' '{print $2}') / 1000000 ))Mhz" ;;
"bcm53xx"/*)
	cpu_freq="$(nvram get clkfreq | awk -F ',' '{print $1}')MHz" ;;
"rockchip"/*|\
"sunxi/cortexa53")
	cpu_freq="$(awk '{printf("%.fMHz ", $0 / 1000)}' "$CPUFREQ_PATH"/policy*/cpuinfo_cur_freq | awk '$1=$1')" ;;
"x86"/*)
	cpu_freq="$(awk -F ': ' '/MHz/ {print $2}' "$CPUINFO_PATH" | head -n1)MHz" ;;
*)
	[ ! -e "$CPUFREQ_PATH/policy0/cpuinfo_cur_freq" ] || \
		cpu_freq="$(awk '{printf("%.fMHz", $0 / 1000)}' "$CPUFREQ_PATH/policy0/cpuinfo_cur_freq")"
	;;
esac

case "$DISTRIB_TARGET" in
"bcm27xx"/*)
	cpu_temp="$(vcgencmd measure_temp | awk -F '=' '{print $2}' | awk -F "'" '{print $1}')°C" ;;
"ipq40xx"/*|"ipq806x"/*|"mediatek"/*|"qualcommax"/*) ;;
"x86"/*)
	if [ -n "$(uci -q get "wechatpush.config.server_host")" ]; then
		cpu_temp="$(/usr/share/wechatpush/wechatpush soc)°C"
	else
		cpu_temp="$(read_cpu_temp)"
	fi
	;;
*)
	[ ! -e "$THERMAL_PATH/thermal_zone0/temp" ] || \
		cpu_temp="$(awk '{printf("%.1f°C", $0 / 1000)}' "$THERMAL_PATH/thermal_zone0/temp")"
	;;
esac

if [ -z "$cpu_freq" ] && [ -n "$cpu_temp" ]; then
	echo -n "$cpu_arch x $cpu_cores ($cpu_temp)"
elif [ -z "$cpu_temp" ] && [ -n "$cpu_freq" ]; then
	echo -n "$cpu_arch x $cpu_cores ($cpu_freq)"
elif [ -n "$cpu_temp" ] && [ -n "$cpu_freq" ]; then
	echo -n "$cpu_arch x $cpu_cores ($cpu_freq, ${cpu_temp})"
else
	echo -n "$cpu_arch x $cpu_cores"
fi
