#!/bin/sh

IEEE_PATH="/sys/class/ieee80211"
THERMAL_PATH="/sys/class/thermal"
HWMON_PATH="/sys/class/hwmon"

format_temp_file() {
	awk '
	/^[+-]?[0-9]+(\.[0-9]+)?$/ {
		temp = $1 + 0
		if (temp > 1000 || temp < -1000)
			temp = temp / 1000
		if (temp > 0 && temp < 130) {
			printf("%.1fC", temp)
			exit
		}
	}' "$1" 2>"/dev/null"
}

read_temp_from_hwmon() {
	for hwmon in "$HWMON_PATH"/hwmon*; do
		[ -d "$hwmon" ] || continue

		name="$(cat "$hwmon/name" 2>"/dev/null")"
		case "$name" in
		coretemp|k10temp|zenpower|x86_pkg_temp|cpu_thermal|cpu-thermal|soc_dts*)
			for input in "$hwmon"/temp*_input; do
				[ -r "$input" ] || continue
				temp="$(format_temp_file "$input")"
				[ -n "$temp" ] && {
					echo -n "$temp"
					return 0
				}
			done
			;;
		esac
	done

	for hwmon in "$HWMON_PATH"/hwmon*; do
		[ -d "$hwmon" ] || continue

		name="$(cat "$hwmon/name" 2>"/dev/null")"
		case "$name" in
		acpitz|pch_*|INT34*)
			for input in "$hwmon"/temp*_input; do
				[ -r "$input" ] || continue
				temp="$(format_temp_file "$input")"
				[ -n "$temp" ] && {
					echo -n "$temp"
					return 0
				}
			done
			;;
		esac
	done

	return 1
}

read_temp_from_thermal_zone() {
	for zone in "$THERMAL_PATH"/thermal_zone*; do
		[ -r "$zone/temp" ] || continue

		type="$(cat "$zone/type" 2>"/dev/null")"
		case "$type" in
		*x86_pkg_temp*|*coretemp*|*Core*|*core*|*soc_dts*|*SoC*|*soc*|*CPU*|*cpu*)
			temp="$(format_temp_file "$zone/temp")"
			[ -n "$temp" ] && {
				echo -n "$temp"
				return 0
			}
			;;
		esac
	done

	for zone in "$THERMAL_PATH"/thermal_zone*; do
		[ -r "$zone/temp" ] || continue

		type="$(cat "$zone/type" 2>"/dev/null")"
		case "$type" in
		*acpitz*|*Thermal*|*thermal*|*pch*|*INT34*)
			temp="$(format_temp_file "$zone/temp")"
			[ -n "$temp" ] && {
				echo -n "$temp"
				return 0
			}
			;;
		esac
	done

	for zone in "$THERMAL_PATH"/thermal_zone*; do
		[ -r "$zone/temp" ] || continue

		temp="$(format_temp_file "$zone/temp")"
		[ -n "$temp" ] && {
			echo -n "$temp"
			return 0
		}
	done

	return 1
}

read_cpu_temp() {
	temp="$(read_temp_from_hwmon)"
	[ -n "$temp" ] && {
		echo -n "$temp"
		return 0
	}

	temp="$(read_temp_from_thermal_zone)"
	[ -n "$temp" ] && {
		echo -n "$temp"
		return 0
	}

	command -v sensors >/dev/null 2>&1 || return 1
	sensors -u 2>"/dev/null" | awk '
	/^[[:space:]]*temp[0-9]+_input:/ {
		temp = $2 + 0
		if (temp > 0 && temp < 130) {
			printf("%.1fC", temp)
			exit
		}
	}'
}

if grep -Eq "ipq40xx|ipq806x" "/etc/openwrt_release"; then
	wifi_temp="$(awk '{printf("%.1fC ", $0 / 1000)}' "$IEEE_PATH"/phy*/device/hwmon/hwmon*/temp1_input 2>"/dev/null" | awk '$1=$1')"
else
	wifi_temp="$(cat "$IEEE_PATH"/phy*/hwmon*/temp1_input 2>"/dev/null" | awk '{printf("%.1fC ", $0 / 1000)}' | awk '$1=$1')"
fi

if grep -q "ipq40xx" "/etc/openwrt_release"; then
	if [ -e "$IEEE_PATH/phy0/hwmon0/temp1_input" ]; then
		mt76_temp="$(awk -F ': ' '{print $2}' "$IEEE_PATH/phy0/hwmon0/temp1_input" 2>"/dev/null")°C"
	fi
	[ -z "$mt76_temp" ] || wifi_temp="${wifi_temp:+$wifi_temp }$mt76_temp"
else
	cpu_temp="$(read_cpu_temp)"
fi

if [ -n "$cpu_temp" ] && [ -z "$wifi_temp" ]; then
	echo -n "CPU: $cpu_temp"
elif [ -z "$cpu_temp" ] && [ -n "$wifi_temp" ]; then
	echo -n "WiFi: $wifi_temp"
elif [ -n "$cpu_temp" ] && [ -n "$wifi_temp" ]; then
	echo -n "CPU: $cpu_temp, WiFi: $wifi_temp"
else
	echo -n "No temperature info"
fi
